###### Numpy random package:

In [1]:
from numpy import random
print(random.randint(1,100))
print(random.rand())

38
0.49367620324808825


In [2]:
#creating n - dimensional array with random elemnents
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[28 79 15]
[[67 97 51 11]
 [37 53  0 54]
 [31 81 49 29]]
[[[69 72]
  [13 36]
  [99  7]
  [ 4  1]]

 [[24 88]
  [91 43]
  [50 78]
  [80 46]]

 [[52 94]
  [86 19]
  [16 81]
  [62 47]]]


In [3]:
#creating n-dimensional array with random integer
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.1845186532624845
[0.94648955 0.50738482 0.00711148]
[[0.3426749  0.3729151  0.26837598]
 [0.45793075 0.20334797 0.12743929]]


In [4]:
a = random.randint(100,size = (3,2)).ravel()
a

array([53, 92, 97, 91, 94,  0])

In [5]:
# single element will be selected
random.choice(a)

0

In [6]:
#for generating an array eith the given shape and elements from given set
random.choice([1,2,3,4,5],size=(4,4))

array([[2, 1, 4, 3],
       [3, 3, 5, 4],
       [1, 3, 4, 4],
       [3, 5, 1, 3]])

### Pandas :
1. Data Manipulation , analysis and cleaning
2. Tabular Data ,orderd and unordered,unlabelled
### creating a Dataframe
- using two dictionaries
-  simple dictionary --->Data frame

In [10]:
#using 2 dictionaries
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data = {"first":dict1,"second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df

first  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [11]:
#simple dictionary ---> dataframe
d1 = {"name":["nikhila","kavya","pranathi","nandini"],"address":["acpt","srd","sdpt","kadapa"]}
df1 = pd.DataFrame(d1)
df1

name address
0   nikhila    acpt
1     kavya     srd
2  pranathi    sdpt
3   nandini  kadapa

In [12]:
#using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,45.3,45.5,36.5,10.9,5.06,3.6,7.5,40.60])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data  = {"column1":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    36.50       e
5        6    10.90       f
6        7     5.06       g
7        8     3.60       h
8        9     7.50       i
9       10    40.60       j

###### Selecting the data from the Data frame:
1. loc
2. iloc

In [13]:
df3["column2"]

0    12.23
1    23.34
2    45.30
3    45.50
4    36.50
5    10.90
6     5.06
7     3.60
8     7.50
9    40.60
Name: column2, dtype: float64

In [14]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    45.30       c
3    45.50       d
4    36.50       e
5    10.90       f
6     5.06       g
7     3.60       h
8     7.50       i
9    40.60       j

In [15]:
#single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [16]:
#Extracting multiple column values
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    36.50
5        6    10.90

In [17]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [18]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### differences:
1. loc -->row and columns labels
2. iloc -->

##### Retrieving the information of Dataframe

In [19]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
column1    10 non-null int64
column2    10 non-null float64
column3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [20]:
df3.shape

(10, 3)

In [21]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [22]:
df3.index

RangeIndex(start=0, stop=10, step=1)

In [23]:
df3.head()

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    36.50       e

###### viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [24]:
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c

In [25]:
df3.tail()

column1  column2 column3
5        6    10.90       f
6        7     5.06       g
7        8     3.60       h
8        9     7.50       i
9       10    40.60       j

In [26]:
df3.tail(2)

column1  column2 column3
8        9      7.5       i
9       10     40.6       j

In [27]:
df3.sample() 

column1  column2 column3
6        7     5.06       g

In [28]:
df3.sample(2)

column1  column2 column3
9       10     40.6       j
5        6     10.9       f

In [29]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  23.053000
std     3.02765  17.309259
min     1.00000   3.600000
25%     3.25000   8.350000
50%     5.50000  17.785000
75%     7.75000  39.575000
max    10.00000  45.500000

###### Renaming columns:

In [30]:
df3 = df3.rename(columns={"column1":"First",
                   "column2":"Second",
                   "column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   36.50     e
5      6   10.90     f
6      7    5.06     g
7      8    3.60     h
8      9    7.50     i
9     10   40.60     j

In [31]:
arr1 = np.arange(9).reshape(3,3)

arr1[:,[1,2]] = arr1[:,[2,1]]

print(arr1)

[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [32]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])

c=np.append(a,b,axis=1)

print(c)

[[ 1  2  3 11 21 31]
 [ 4  5  6 42 52 62]
 [ 7  8  9 73 83 93]]


In [36]:
a = np.arange(10).reshape(2,-1)

In [37]:
b = np.repeat(1, 10).reshape(2,-1)

In [35]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

n = 5